import { ClaimItem } from "../types";
import { ListChecks, X, ShieldCheck, Database, Layers } from "lucide-react";

interface ClaimsInspectorProps {
  claims: ClaimItem[];
  isOpen: boolean;
  onClose: () => void;
}

export function ClaimsInspector({ claims, isOpen, onClose }: ClaimsInspectorProps) {
  if (!isOpen) return null;

  return (
    <div className="flex flex-col h-full bg-white dark:bg-slate-900 border-l border-slate-200 dark:border-slate-800 p-4 overflow-y-auto">
      {/* Header */}
      <div className="flex items-center justify-between pb-3 border-b border-slate-200 dark:border-slate-800 mb-4">
        <div className="flex items-center gap-2">
          <div className="w-7 h-7 rounded-lg bg-emerald-100 dark:bg-emerald-950/60 text-emerald-600 dark:text-emerald-400 flex items-center justify-center">
            <ListChecks className="w-4 h-4" />
          </div>
          <div>
            <h3 className="text-sm font-bold text-slate-800 dark:text-slate-100">
              Claims Inspector
            </h3>
            <p className="text-[11px] text-slate-400">
              {claims.length} atomic {claims.length === 1 ? "claim" : "claims"} extracted
            </p>
          </div>
        </div>

        <button
          type="button"
          onClick={onClose}
          className="p-1.5 rounded-lg text-slate-400 hover:text-slate-700 dark:hover:text-slate-200 hover:bg-slate-100 dark:hover:bg-slate-800 transition-colors"
          aria-label="Close claims inspector"
        >
          <X className="w-4 h-4" />
        </button>
      </div>

      {/* Milestone 1 Contract Badge */}
      <div className="p-3 rounded-xl bg-slate-50 dark:bg-slate-950/50 border border-slate-200 dark:border-slate-800 mb-4 text-xs space-y-1.5">
        <div className="flex items-center gap-1.5 font-semibold text-emerald-700 dark:text-emerald-400">
          <ShieldCheck className="w-3.5 h-3.5" />
          <span>Milestone 1 Data Contract</span>
        </div>
        <p className="text-slate-500 dark:text-slate-400 text-[11px] leading-relaxed">
          Every statement generated by the model is decomposed into discrete factual claims. All source citations are strictly forced to <code className="px-1 py-0.5 rounded-sm bg-slate-200 dark:bg-slate-800 font-mono text-emerald-600 dark:text-emerald-400">null</code> until external retrieval is connected.
        </p>
      </div>

      {/* Extracted Claims List */}
      <div className="space-y-2.5 mb-6 flex-1">
        <h4 className="text-xs font-semibold text-slate-500 dark:text-slate-400 uppercase tracking-wider">
          Extracted Claims
        </h4>

        {claims.length === 0 ? (
          <div className="p-4 rounded-xl border border-dashed border-slate-200 dark:border-slate-800 text-center text-xs text-slate-400">
            Click on &quot;Claims Extracted&quot; in any assistant answer to inspect its atomic statements.
          </div>
        ) : (
          claims.map((claim, index) => (
            <div
              key={index}
              className="p-3 rounded-xl bg-slate-50 dark:bg-slate-950/40 border border-slate-200 dark:border-slate-800 text-xs space-y-1.5 shadow-2xs"
            >
              <div className="flex items-start gap-2">
                <span className="w-4 h-4 rounded-full bg-emerald-100 dark:bg-emerald-950 text-emerald-700 dark:text-emerald-300 flex items-center justify-center font-mono text-[10px] shrink-0 font-bold mt-0.5">
                  {index + 1}
                </span>
                <p className="text-slate-800 dark:text-slate-200 font-medium leading-relaxed">
                  {claim.claim_text}
                </p>
              </div>

              <div className="flex items-center justify-between pt-1 border-t border-slate-200/60 dark:border-slate-800/60 text-[11px]">
                <span className="text-slate-400 flex items-center gap-1">
                  <Database className="w-3 h-3" />
                  Source:
                </span>
                <span className="px-1.5 py-0.5 rounded-sm bg-slate-200 dark:bg-slate-800 text-slate-600 dark:text-slate-300 font-mono text-[10px]">
                  {claim.source === null ? "null (Parametric)" : claim.source}
                </span>
              </div>
            </div>
          ))
        )}
      </div>

      {/* Milestone 2 Forward Compatibility Placeholder Slots */}
      <div className="pt-4 border-t border-slate-200 dark:border-slate-800 space-y-2">
        <div className="flex items-center gap-1.5 text-xs font-semibold text-slate-700 dark:text-slate-300">
          <Layers className="w-3.5 h-3.5 text-emerald-600 dark:text-emerald-400" />
          <span>Milestone 2 Citations Pre-Allocation</span>
        </div>
        <p className="text-[11px] text-slate-400 leading-relaxed">
          These slots will display USDA FoodData Central and scientific literature citations once RAG indexing is activated:
        </p>

        <div className="space-y-1.5">
          <div className="p-2 rounded-lg border border-dashed border-slate-200 dark:border-slate-800 text-[11px] text-slate-400 flex items-center gap-2">
            <span className="w-2 h-2 rounded-full bg-slate-300 dark:bg-slate-700" />
            <span>[Slot 1] USDA FoodData Central Index (Pending M2)</span>
          </div>
          <div className="p-2 rounded-lg border border-dashed border-slate-200 dark:border-slate-800 text-[11px] text-slate-400 flex items-center gap-2">
            <span className="w-2 h-2 rounded-full bg-slate-300 dark:bg-slate-700" />
            <span>[Slot 2] NIH Dietary Reference Intake (Pending M2)</span>
          </div>
          <div className="p-2 rounded-lg border border-dashed border-slate-200 dark:border-slate-800 text-[11px] text-slate-400 flex items-center gap-2">
            <span className="w-2 h-2 rounded-full bg-slate-300 dark:bg-slate-700" />
            <span>[Slot 3] FDA Food Code / Safe Storage Guide (Pending M2)</span>
          </div>
        </div>
      </div>
    </div>
  );
}
